spring:
  datasource:
    url: jdbc:mysql://101.43.43.87:3306/jitamin?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 180.76.236.108
    port: 6379
    database: 4
    timeout:  1000s
    password:
    #  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show-sql: true
#        format_sql: true

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: geektime.spring.springbucks
